# Generated by Django 2.2.27 on 2022-03-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeURL', models.CharField(max_length=255)),
                ('insertDate', models.DateTimeField()),
            ],
        ),
    ]
